<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Activation email' => 'Email d\'activation',
'This email has already been taken.' => 'عنوان بريد الكتروني محجوز مسبقاً .',
'Your account has been successfully activated.' => 'تم تفعيل حسابك بنجاح.',
'Your account has been successfully created. Check your email for further instructions.' => 'تم خلق حسابك, فضلاً راجع صندوق بريدك الالكتروني لمعرفة الخطوة التالية.',
'Your activation link: {url}' => 'رابط التفعيل: {url}',
'About' => 'إعرف عنا ',
'Account Settings' => 'إعدادات الحساب',
'Articles' => 'مقالات',
'Attachments' => 'مرفقات',
'Backend' => 'الورائية',
'Body' => 'المتن',
'Check your email for further instructions.' => 'راجع صندوق بريدك الالكتروني من اجل تعليمات اضافية.',
'Confirm Password' => 'تأكيد كلمة المرور',
'Contact' => 'معلومات الاتصال',
'E-mail' => 'بريد الكتروني',
'Email' => 'بريد الكتروني',
'Error while oauth process.' => 'وقع خطأ خلال المصادقة OAuth.',
'Female' => 'أنثى',
'Home' => 'الرئيسية',
'If you forgot your password you can reset it <a href="{link}">here</a>' => 'اذا كنت قد نسيت كلمة السر يمكنك إعادة ضبطها <a href="{link}">هنا</a>',
'Incorrect username or password.' => 'إسم مستخدم او كلمة سر خاطئة.',
'Language' => 'اللغة',
'Log in with' => 'ولوج بإستخدام',
'Login' => 'ولوج',
'Logout' => 'خروج',
'Male' => 'ذكر',
'Name' => 'الإسم',
'Need an account? Sign up.' => 'ألا تملك حساب؟, إشترك.',
'New password was saved.' => 'كلمة السر الجديدة خزّنت.',
'Page not found' => 'الصفحة غير موجودة',
'Password' => 'كلمة السر',
'Password reset for {name}' => 'إعادة تعيين كلمة السر الخاصة بـ {name}',
'Profile settings' => 'إعدادات صفحة التعريف',
'Remember Me' => 'تذكرني',
'Request password reset' => 'أطلب إعادة تعيين كلمة السر',
'Reset password' => 'إعادة تعيين كلمة السر',
'Settings' => 'إعدادات',
'Sign up with' => 'إشتراك بإستخدام',
'Signup' => 'إشتراك',
'Sorry, we are unable to reset password for email provided.' => 'عذراً, غير ممكن إعادة تعيين كلمة السر المرتبطة بهذا البريد الالكتروني .',
'Subject' => 'الموضوع',
'Submit' => 'إرسال',
'Thank you for contacting us. We will respond to you as soon as possible.' => 'نشكر لك رسالتك, سنقوم بالرد عليها باقرب وقت ممكن.',
'There was an error sending email.' => 'وقع خطأ خلال إرسال البريد الالكتروني.',
'This email address has already been taken.' => 'عنوان بريد الكتروني محجوز مسبقاً.',
'This username has already been taken.' => 'إسم مستخدم محجوز مسبقاً.',
'Update' => 'تحديث ',
'User Settings' => 'إعدادات المستخدم',
'Username' => 'إسم المستخدم',
'Username or email' => 'إسم المستخدم او البريد الالكتروني',
'Verification Code' => 'رمز التحقق',
'We already have a user with email {email}' => 'عنوان بريد الكتروني محجوز مسبقاً {email}',
'Welcome to {app-name}. Email with your login information was sent to your email.' => 'اهلا وسهلا بك على  {app-name}. أرسلنا على بريدك الالكتروني معلومات الولوج خاصتك.',
'Your account has been successfully saved' => 'تم تسجيل حسابك بنجاح',
'{app-name} | Your login information' => '{app-name} | معلومات الولوج',
];
